### ISSUE TITLE
What books did you enjoy reading lately?

### ISSUE THREAD

**Issue by arthurvr** [tonyynot/ama#1]

**Comment by tonyynot** [comment]
Programming books:
**The Modern Web** by Peter Gasston - focused on multi-device front end development
**Javascript & JQuery** by Jon Duckett - very thorough crash course on javascript and jquery fundamentals. It sits within arms reach on my desk at work and serves as a great reference.
**The Guide to ExpressionEngine Development** by Ryan Masuga - excellent guide to the CMS I use at my job, covers lots of helpful coding practices and version control tips.

Other:
**Slaughterhouse Five** by Kurt Vonnegut - Not finished with it but its amazing so far. Classic novel that I never got around to reading up until now.
**Black Hole** by Charles Burns - incredible sci-fi graphic novel that takes place in the 70s, all black & white. Highly recommended if you're into graphic novels.
