### ISSUE TITLE
What languages do you specialize in? And do you recommend one to learn Javascript (thereby can use all its frameworks like Angular or the MEAN stack) or Ruby on Rails for developing Web Apps?

### ISSUE THREAD

**Issue by Ridwansameer** [tonyynot/ama#3]
Just wanted to pick your mind about it :)

**Comment by tonyynot** [comment]
Right now I specialize in front end languages, I'd say I'm strongest with CSS. I work with PHP on the back end so I've been picking up a little of that, although I would have a difficult time with it had I not learned JavaScript first. Learning Javascript I think is a great introduction to programming languages and will make PHP or Ruby come easier if you chose to go down that road. 

I will say that I have worked an internship at an Angular shop before so I got some hands on with it and its a very powerful framework. Same goes for a few other JS based frameworks such as Meteor, Backbone and React. To me it makes more sense to specialize on the front end and build your JS skills to the level where you can create back end functionality with one of those frameworks. JS frameworks seem to be the wave of the future and although there are plenty of high paying jobs for Ruby devs, I think in the long run it might be more rewarding to be on the cutting edge.
